<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'doctrine.fixtures_load_command' shared service.

$a = new \Doctrine\Bundle\FixturesBundle\Loader\SymfonyFixturesLoader($this);
$a->addFixtures([0 => ['fixture' => ${($_ = isset($this->services['AppBundle\\DataFixtures\\ORM\\LoadUserData']) ? $this->services['AppBundle\\DataFixtures\\ORM\\LoadUserData'] : ($this->services['AppBundle\\DataFixtures\\ORM\\LoadUserData'] = new \AppBundle\DataFixtures\ORM\LoadUserData())) && false ?: '_'}, 'groups' => []]]);

$this->services['doctrine.fixtures_load_command'] = $instance = new \Doctrine\Bundle\FixturesBundle\Command\LoadDataFixturesDoctrineCommand($a, ${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'});

$instance->setName('doctrine:fixtures:load');

return $instance;
