<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

return $this->services['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(['Bookstore\\DefaultBundle\\Controller\\SecurityController:loginAction' => function () {
    return ${($_ = isset($this->services['service_locator.drdp9yf']) ? $this->services['service_locator.drdp9yf'] : $this->load('getServiceLocator_Drdp9yfService.php')) && false ?: '_'};
}, 'Bookstore\\DefaultBundle\\Controller\\SecurityController::loginAction' => function () {
    return ${($_ = isset($this->services['service_locator.drdp9yf']) ? $this->services['service_locator.drdp9yf'] : $this->load('getServiceLocator_Drdp9yfService.php')) && false ?: '_'};
}]));
