<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'AppBundle\DataFixtures\ORM\LoadFixtureData' shared service.

return $this->services['AppBundle\\DataFixtures\\ORM\\LoadFixtureData'] = new \AppBundle\DataFixtures\ORM\LoadFixtureData();
