<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX2tgcml\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX2tgcml/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerX2tgcml.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerX2tgcml\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerX2tgcml\appDevDebugProjectContainer([
    'container.build_hash' => 'X2tgcml',
    'container.build_id' => '7408bf96',
    'container.build_time' => 1589802043,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX2tgcml');
