<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW3grxlg\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW3grxlg/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerW3grxlg.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerW3grxlg\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerW3grxlg\appDevDebugProjectContainer([
    'container.build_hash' => 'W3grxlg',
    'container.build_id' => 'a27d1285',
    'container.build_time' => 1589888679,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW3grxlg');
